<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Akshay Regulagedda">
<meta name="dcterms.date" content="2023-07-23">
<meta name="description" content="‘Twentieth anniversary edition’ of my undergraduate thesis on the Indic calendar system.">

<title>aksh.ai - Panchanga Tantra: The Magic of the Indic Calendar System</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-N0W83S6B2J"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-N0W83S6B2J', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="aksh.ai - Panchanga Tantra: The Magic of the Indic Calendar System">
<meta property="og:description" content="‘Twentieth anniversary edition’ of my undergraduate thesis on the Indic calendar system.">
<meta property="og:image" content="https://www.aksh.ai/posts/panchanga-tantra/kala-chakra.png">
<meta property="og:site_name" content="aksh.ai">
<meta property="og:image:height" content="2284">
<meta property="og:image:width" content="2538">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">aksh.ai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://social.vivaldi.net/@cydonian"> <i class="bi bi-mastodon" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/akshr/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.instagram.com/metamutator/"> <i class="bi bi-instagram" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#foreword" id="toc-foreword" class="nav-link active" data-scroll-target="#foreword">0. Foreword</a>
  <ul class="collapse">
  <li><a href="#th-anniversary-edition-2023" id="toc-th-anniversary-edition-2023" class="nav-link" data-scroll-target="#th-anniversary-edition-2023">20th Anniversary Edition (2023)</a></li>
  <li><a href="#second-edition-2002" id="toc-second-edition-2002" class="nav-link" data-scroll-target="#second-edition-2002">Second Edition (2002)</a></li>
  </ul></li>
  <li><a href="#prologue-the-mystical-garden-of-enchanted-numbers" id="toc-prologue-the-mystical-garden-of-enchanted-numbers" class="nav-link" data-scroll-target="#prologue-the-mystical-garden-of-enchanted-numbers">1. <em>Prologue</em>: The Mystical Garden of Enchanted Numbers</a></li>
  <li><a href="#sthaana-prakarana-how-the-calendar-is-different-in-different-regions" id="toc-sthaana-prakarana-how-the-calendar-is-different-in-different-regions" class="nav-link" data-scroll-target="#sthaana-prakarana-how-the-calendar-is-different-in-different-regions">2. <em>Sthaana Prakarana</em>: How the calendar is different in different regions</a>
  <ul class="collapse">
  <li><a href="#the-southern-amaanta-calendar" id="toc-the-southern-amaanta-calendar" class="nav-link" data-scroll-target="#the-southern-amaanta-calendar">2.1 The Southern Amaanta Calendar</a></li>
  <li><a href="#western-amaanta-calendar" id="toc-western-amaanta-calendar" class="nav-link" data-scroll-target="#western-amaanta-calendar">2.2 Western Amaanta Calendar</a></li>
  <li><a href="#purnimaanta-calendar" id="toc-purnimaanta-calendar" class="nav-link" data-scroll-target="#purnimaanta-calendar">2.3 Purnimaanta Calendar</a></li>
  <li><a href="#the-malayali-calendar" id="toc-the-malayali-calendar" class="nav-link" data-scroll-target="#the-malayali-calendar">2.5 The Malayali&nbsp;Calendar</a></li>
  <li><a href="#tamil-calendar" id="toc-tamil-calendar" class="nav-link" data-scroll-target="#tamil-calendar">2.6 Tamil Calendar</a></li>
  <li><a href="#bengali-calendar" id="toc-bengali-calendar" class="nav-link" data-scroll-target="#bengali-calendar">2.7 Bengali Calendar</a></li>
  <li><a href="#oriya-calendar" id="toc-oriya-calendar" class="nav-link" data-scroll-target="#oriya-calendar">2.8 Oriya Calendar</a></li>
  <li><a href="#the-nanakshahi-calendar" id="toc-the-nanakshahi-calendar" class="nav-link" data-scroll-target="#the-nanakshahi-calendar">2.9 The Nanakshahi Calendar</a></li>
  <li><a href="#national-calendar-of-1957" id="toc-national-calendar-of-1957" class="nav-link" data-scroll-target="#national-calendar-of-1957">2.10 National Calendar of&nbsp;1957</a></li>
  </ul></li>
  <li><a href="#maasa-naamakarana-how-the-months-got-their-names." id="toc-maasa-naamakarana-how-the-months-got-their-names." class="nav-link" data-scroll-target="#maasa-naamakarana-how-the-months-got-their-names.">3. <em>Maasa Naamakarana</em>: How the Months got their&nbsp;Names.</a>
  <ul class="collapse">
  <li><a href="#months-named-after-nakshatras" id="toc-months-named-after-nakshatras" class="nav-link" data-scroll-target="#months-named-after-nakshatras">3.1 Months named after Nakshatras</a></li>
  <li><a href="#months-named-after-raasis" id="toc-months-named-after-raasis" class="nav-link" data-scroll-target="#months-named-after-raasis">3.2 Months named after Raasis</a></li>
  </ul></li>
  <li><a href="#parva-dina-nirnaya-how-the-days-of-festivals-are-decided." id="toc-parva-dina-nirnaya-how-the-days-of-festivals-are-decided." class="nav-link" data-scroll-target="#parva-dina-nirnaya-how-the-days-of-festivals-are-decided.">4. <em>Parva Dina&nbsp;Nirnaya</em>: How the days of festivals are&nbsp;decided.</a></li>
  <li><a href="#samvad-sandesha-how-eras-come-into-play" id="toc-samvad-sandesha-how-eras-come-into-play" class="nav-link" data-scroll-target="#samvad-sandesha-how-eras-come-into-play">5. <em>Samvad Sandesha</em>: How Eras come into play</a></li>
  <li><a href="#kshaya-sutra-how-certain-months-are-dropped" id="toc-kshaya-sutra-how-certain-months-are-dropped" class="nav-link" data-scroll-target="#kshaya-sutra-how-certain-months-are-dropped">6. <em>Kshaya Sutra</em>: How certain months are&nbsp;dropped</a>
  <ul class="collapse">
  <li><a href="#treatment-of-kshaya-months" id="toc-treatment-of-kshaya-months" class="nav-link" data-scroll-target="#treatment-of-kshaya-months">6.1 Treatment of Kshaya Months</a></li>
  </ul></li>
  <li><a href="#epilogue" id="toc-epilogue" class="nav-link" data-scroll-target="#epilogue">7. Epilogue</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">8. References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">9. Appendix</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Panchanga Tantra: The Magic of the Indic Calendar System</h1>
  <div class="quarto-categories">
    <div class="quarto-category">mathematics</div>
    <div class="quarto-category">astronomy</div>
    <div class="quarto-category">calendar</div>
  </div>
  </div>

<div>
  <div class="description">
    ‘Twentieth anniversary edition’ of my undergraduate thesis on the Indic calendar system.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Akshay Regulagedda </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 23, 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="fig-kalachakra" class="quarto-figure quarto-figure-left quarto-float anchored" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kalachakra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kala-chakra.png" class="img-fluid quarto-figure quarto-figure-left figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kalachakra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Kala Chakra
</figcaption>
</figure>
</div>
<section id="foreword" class="level2">
<h2 class="anchored" data-anchor-id="foreword">0. Foreword</h2>
<section id="th-anniversary-edition-2023" class="level3">
<h3 class="anchored" data-anchor-id="th-anniversary-edition-2023">20th Anniversary Edition (2023)</h3>
<p>This is a “20th anniversary edition” of a thesis I wrote in 2002 for the Undergraduate Research Opportunities Programme (UROP), as part of my mathematics minor in the National University of Singapore. This is also a word-for-word republishing of the thesis, but with updates to embed graphics and tables within the text. All errors (if any) are mine, and have existed for 20+ years.</p>
<p>For the longest time, this thesis was up on my then supervisor, Dr Helmer Aslaksen’s website at the Mathematics Department’s webpage. During this time, a great many had downloaded the PDF, but very few presumably understood it. For, this undergrad thesis found it its way to websites talking about dark magic and other related mystical concepts. Probably they got confused with the “tantra” in the title. Didn’t help that I made this mystical-looking, but perfectly scientific, graphic alluding to kaala chakra’s that would presumably sound woo-woo to unsuspecting audiences. Incidentally, I just re-did this graphic (<a href="#fig-kalachakra" class="quarto-xref">Figure&nbsp;1</a>) to more exacting design standards, and perhaps would warrant another detailed explanation.</p>
<p>Dr Aslaksen returned to Oslo many many moons ago (pun intended). His old webpage at NUS’ website was still active for many years later, but now that it too has gone, I’m now back on the Internet to say this: nothing tantric about it. I was just punning between the Sanskrit terms ‘panchatantra’ and ‘panchangam’. In fact, this is all mathematic exploration and research, by way of Vedanga Jyotisa, Surya Siddhanta, and modelling all of those principles in Java and LISP. This is me doing that roots thing but via math. This is me claiming expertise in Indic, Chinese and Islamic calendars, of being able to tell when Chinese New Year and Deepavali can fall. Akshay researching kshaya months, if you will. That is all there is to it. Magical, but no black magic.</p>
<p>There is one literary conceit, though.</p>
</section>
<section id="second-edition-2002" class="level3">
<h3 class="anchored" data-anchor-id="second-edition-2002">Second Edition (2002)</h3>
<p>The fable of Apara Ganita and the Mystical Garden of Enchanted Numbers is obviously fictional. The inspiration is <em>Leelavati Ganitam</em>, a chapter in the ancient mathematical treatise, the <em>Siddhanta Siromani</em>, written by Bhaskaracharya in 1150 CE. The <em>Leelavati Ganitam</em> is fascinating not only for its treatment of indeterminate analysis and a method to solve Pell’s Equation, but also, as a Canadian university’s website on mathematical history puts it<span class="citation" data-cites="simonfraser">(<a href="#ref-simonfraser" role="doc-biblioref">University 2002</a>)</span>, for its poetic conversation between the narrator and a narratee named Leelavati. The similarity between this poetic construct and the conversation between Apara Ganita and the dwara palika is probably noticeable.</p>
<p>Frame stories are not common for scientific research papers, but they certainly have a historical precedent.</p>
</section>
</section>
<section id="prologue-the-mystical-garden-of-enchanted-numbers" class="level2">
<h2 class="anchored" data-anchor-id="prologue-the-mystical-garden-of-enchanted-numbers">1. <em>Prologue</em>: The Mystical Garden of Enchanted Numbers</h2>
<p><em>Once upon a time, in the magical mystical city of Suvarnapuri<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, there lived a student called Apara Ganita<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Apara Ganita was virtuous and devoted to his sciences. Having spent considerable amount of time learning the shastras from his guru, he was surprised when one day his guru called him up. “You have performed well, O sishya⁴ mine”, the guru said, “but the time has now come for you to take leave”.</em></p>
<p><em>Apara Ganita was at once sad, for he had learned a lot under him. But he remained quiet and continued listening to his guru.</em></p>
<p><em>“Listen, Apara Ganita, I shall now tell you something that my guru told me when I finished my studies. For, a study in Ganita Sastra (mathematics) is not complete, unless one visits the Mystical Garden of Enchanted Numbers”</em></p>
<p><em>“You must go and find this place for your education to be truly complete”.</em></p>
<p><em>And so Apara Ganita went about searching for this place. Indeed, after much travelling and searching, he was finally shown the way to the Mystical Garden of Enchanted Numbers.</em></p>
<p><em>And lo, what a beautiful sight it was! For it was situated in the midst of a lush green valley, saddled by mountains on either side. Down there, Apara Ganita could see famous mathematicians expositing their theories and skills, like hawkers on a bazaar street. There was Euclid standing on a rectangle, explaining the beauty of the Golden Ratio in classic Greco Caldean architecture. Pythagoras was standing next to him as a part of the Greek exhibit, explaining the virtues of a right-angled triangle to a curious crowd. From the far end of the Orator’s Corner, Zhao Jun Qing looked at Pythagoras and smiled. He was himself holding a right-angled triangle and was explaining his proof for the Pythagoras’ Theorem. Mandelbrot was decorating the Garden with flowers of fractallate beauty. John Nash was close by; he was pointing at a group of women, probably explaining game theory to onlookers around him. In another corner of the garden, (Sector 1729), Srinivasa Ramanujan was vociferously arguing a point with Thomas Hardy.</em></p>
<p><em>It was such an environment that Apara Ganita wanted to enter.</em></p>
<p><em>However, as he was about to enter through the great doors guarding the garden, he heard a sonorous voice calling out his name.</em></p>
<p><em>He stopped and turned around to see who was calling him only to saw a young woman coming towards him. With eyes burning with curiosity and a voice sweeter than a nightingale, she said:</em></p>
<div class="line-block">&nbsp;&nbsp;O Student Erudite,<br>
&nbsp;&nbsp;What is it that you study tonight?</div>
<p><em>Just what I needed, a mystical </em>dwara palika <em>(female door keeper), he said to himself. Shaking his head in wry amusement, he looks at the books in his hand and takes a deep breath to begin his dissertation.</em></p>
</section>
<section id="sthaana-prakarana-how-the-calendar-is-different-in-different-regions" class="level2">
<h2 class="anchored" data-anchor-id="sthaana-prakarana-how-the-calendar-is-different-in-different-regions">2. <em>Sthaana Prakarana</em>: How the calendar is different in different regions</h2>
<div class="line-block"><em>In a sonorous voice, the dwara palika said,</em><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In order to ascertain your dissertation’s veracity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;can I hear you talk about the calendar’s regional complexity?<br>
<em>To which Apara Ganita listened to the multitudes of voices in the Garden, and replied thus:</em></div>
<p>Probably the easiest way to classify Indian calendars is by the region of usage. It must be reiterated though, that such an exercise might be misleading. The classification is indeed not watertight; all calendars are intrinsically inter-linked with one another. A flowchart of the various Indian calendars and the links between them can be seen below (<a href="#fig-caluml" class="quarto-xref">Figure&nbsp;2</a>).</p>
<div id="fig-caluml" class="quarto-figure quarto-figure-left quarto-float anchored" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-caluml-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="calendar-uml.png" class="img-fluid quarto-figure quarto-figure-left figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-caluml-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Indic Calendar System as a quasi-UML diagram
</figcaption>
</figure>
</div>
<p>With this caveat, we’ll now traverse India on a calendrical vehicle of sorts. In particular, we try to ascertain the following elements in each region’s calendrical practices: - * Basis of the Calendar * Local Variation * When does the year begin? * Era Followed</p>
<p>We’ll find the following calendars defined with these metrics: -</p>
<section id="the-southern-amaanta-calendar" class="level3">
<h3 class="anchored" data-anchor-id="the-southern-amaanta-calendar">2.1 The Southern Amaanta Calendar</h3>
<p>The Southern Amaanta Lunisolar Calendar is predominantly followed in the South and South-West Indian states of Andhra Pradesh, Karnataka and Maharashtra. It is essentially a lunisolar one; i.e., its days and months are calculated based on the motions of the moon. Like the Chinese calendar, the month is calculated from new moon to new moon. It however, differs from the Chinese calendar in that the lunar day (“<em>thithi</em>”) of the new moon is considered the last day of the previous month. Again, as in the Chinese calendar, a leap month, an <em>adhika maasa</em>, is added to the calendar every 2.7 years on an average to offset the disparity in lengths between the lunar year and the sidereal year. In addition, a month, the <em>kshaya maasa</em>, is occasionally subtracted. This is discussed in a later segment.</p>
<p>The Southern Amaanta Calendar differs from the Western Amaanta Calendar in its treatment of <em>kshaya maasas</em>, the New Year Day and the Era followed. We believe that the Southern Amaanta Calendar follows the Southern School for treating kshaya maasas. Saha and Lahiri suggest that it follows the Salivahana Saka Era starting with Chaitra Sukla Pratipada <span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 304</a>)</span>, the lunar day after the last new moon before <em>Mesha Sankranti</em>. The years are also named according to the names of the Jovian years (Southern School <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 270</a>)</span>). The Eras and handling of <em>kshaya maasas</em> will be discussed in detail in their respective segments.</p>
</section>
<section id="western-amaanta-calendar" class="level3">
<h3 class="anchored" data-anchor-id="western-amaanta-calendar">2.2 Western Amaanta Calendar</h3>
<p>As already mentioned, we believe it’s important to distinguish between the Amaanta calendar practised in South and West India. In West India, specifically, in the state of Gujarat, the Amaanta calendar is of two forms<span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 304</a>)</span>, one that starts with Aashaadha (followed in the Kathiawar region) and one that starts with Kartika (followed all throughout Gujarat). Both calendars follow the Vikrama Era and both also possibly follow the North Western School for <em>kshaya</em> months.</p>
</section>
<section id="purnimaanta-calendar" class="level3">
<h3 class="anchored" data-anchor-id="purnimaanta-calendar">2.3 Purnimaanta Calendar</h3>
<p>The Purnimaanta Calendar is followed in most of North India, i.e., in the states of Bihar, Himachal Pradesh, Uttar Pradesh, Haryana, Punjab, Jammu and Kashmir and Rajasthan <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 42</a>)</span>. (Earlier literature fails to mention Uttaranchal, Chattisgarh, Jharkhand and Delhi, but they are off-shots of bigger states and would necessarily follow the same calendar). The last of the three Indian lunisolar calendars, this one differs from the Amaanta calendar in that the months are reckoned from full moon to full moon. Therefore, the Purnimaanta calendar starts two weeks before the Amaanta calendar does; that is, it starts with the lunar day after the last full-moon before Mesha Sankranti. The Vikrama Era is followed <span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 305</a>)</span>, along with the Northern School of Jovian-year names <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 270</a>)</span>.</p>
</section>
<section id="the-malayali-calendar" class="level3">
<h3 class="anchored" data-anchor-id="the-malayali-calendar">2.5 The Malayali&nbsp;Calendar</h3>
<p>We now come to the list of Solar Calendars. The Malayali Calendar is predominantly followed in the South Indian state of Kerala. It is essentially a solar calendar; as we shall see later, the months are defined according to the raasis. The year starts with the Simha Sankranti and follows the Kollam Era.<span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 304</a>)</span> The month begins on the same day as a Sankranti if it occurs before aparahna, i.e., three-fifths of a day. Otherwise, it begins on the next day.</p>
</section>
<section id="tamil-calendar" class="level3">
<h3 class="anchored" data-anchor-id="tamil-calendar">2.6 Tamil Calendar</h3>
<p>The Tamil calendar is followed in Tamil Nadu. This calendar is also solar; the month begins on the same day as a Sankranti if it occurs before sunset <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 14</a>)</span>. The Kali Era is followed along with the Southern Jovian cycle. One peculiarity about the Tamil calendar is that its month names start with Chittirai<span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 9</a>)</span> (Chaitra).</p>
</section>
<section id="bengali-calendar" class="level3">
<h3 class="anchored" data-anchor-id="bengali-calendar">2.7 Bengali Calendar</h3>
<p>The Bengali calendar is predominantly followed in West Bengal, Assam and Tripura. The Era is the Bengali San. The rule for the beginning of the month is again different; the month begins on the day after a Sankranti, if it occurs before midnight. Otherwise, it begins on the third day. <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 14</a>)</span></p>
</section>
<section id="oriya-calendar" class="level3">
<h3 class="anchored" data-anchor-id="oriya-calendar">2.8 Oriya Calendar</h3>
<p>The Oriya calendar is followed in the Eastern state of Orissa. In addition to the Bengali San, the Saka, Vilayati and Amli eras are followed. <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 258</a>)</span> The month begins on the same day as that of the respective Sankranti. <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 14</a>)</span></p>
</section>
<section id="the-nanakshahi-calendar" class="level3">
<h3 class="anchored" data-anchor-id="the-nanakshahi-calendar">2.9 The Nanakshahi Calendar</h3>
<p>Promulgated in 1998 CE, the Nanakshahi Calendar is followed in Punjab. It’s intrinsically linked to the Gregorian calendar, except in its usage of the Nanakshahi Era.<span class="citation" data-cites="purewal">(<a href="#ref-purewal" role="doc-biblioref">Purewal 2002</a>)</span></p>
</section>
<section id="national-calendar-of-1957" class="level3">
<h3 class="anchored" data-anchor-id="national-calendar-of-1957">2.10 National Calendar of&nbsp;1957</h3>
<p>Proposed by the Calendar Reform Committee of 1952 and promulgated in 1957 CE, the National Calendar is a tropical calendar with fixed lengths of days and months. However, because it was totally different from the traditional calendars, it did not find much acceptance. <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 18</a>)</span></p>
<p>We may thus summarize Indian calendars thus:</p>
<div class="cell" data-execution_count="1">
<div id="tbl-indian-calendars" class="cell quarto-float anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-indian-calendars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Various Indic Calendars
</figcaption>
<div aria-describedby="tbl-indian-calendars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="1">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">State</th>
<th style="text-align: left;">Calendar</th>
<th style="text-align: left;">Era</th>
<th style="text-align: left;">New Year</th>
<th style="text-align: left;">Further Local Variation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">Andhra Pradesh</td>
<td style="text-align: left;">Southern Amaanta</td>
<td style="text-align: left;">Salivahana Saka, Jovian cycle (Southern School)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;">Possible Jugma month for kshaya</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">Assam</td>
<td style="text-align: left;">Solar</td>
<td style="text-align: left;">Kali, Bengali San</td>
<td style="text-align: left;">Solar Day after Mesha Sankranti</td>
<td style="text-align: left;">Bengali rules for beginning of month</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">Bihar</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last full moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">Chattisgarh</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last full moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">Delhi</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last full moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: left;">Goa</td>
<td style="text-align: left;">Southern Amaanta</td>
<td style="text-align: left;">Salivahana Saka, Jovian cycle (Southern School)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;">Possible Jugma month for kshaya</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="text-align: left;">Gujarat</td>
<td style="text-align: left;">Western Amaanta</td>
<td style="text-align: left;">Vikrama Karthikaadi</td>
<td style="text-align: left;">One day after Deepavali</td>
<td style="text-align: left;">North-western school for kshaya possible</td>
</tr>
<tr class="even">
<td>7</td>
<td style="text-align: left;">Himachal Pradesh</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last full moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: left;">Jammu and Kashmir</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Saptarishi, Laukika</td>
<td style="text-align: left;">One day after the last full moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>9</td>
<td style="text-align: left;">Jharkhand</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last full moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>10</td>
<td style="text-align: left;">(Kathiawar)</td>
<td style="text-align: left;">Western Amaanta</td>
<td style="text-align: left;">Vikrama Aashaadhadi</td>
<td style="text-align: left;">Ashaadha S 1</td>
<td style="text-align: left;">North-western school for kshaya possible</td>
</tr>
<tr class="even">
<td>11</td>
<td style="text-align: left;">Karnataka</td>
<td style="text-align: left;">Southern Amaanta</td>
<td style="text-align: left;">Salivahana Saka, Jovian cycle (Southern School)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;">Possible Jugma month for kshaya</td>
</tr>
<tr class="odd">
<td>12</td>
<td style="text-align: left;">Kerala</td>
<td style="text-align: left;">Solar</td>
<td style="text-align: left;">Kollam Era</td>
<td style="text-align: left;">Simha Sankranti</td>
<td style="text-align: left;">1)&nbsp;&nbsp;&nbsp;&nbsp;Kerala rules for beginning of month</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">2) Months named after raasis</td>
</tr>
<tr class="odd">
<td>13</td>
<td style="text-align: left;">Madhya Pradesh</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>14</td>
<td style="text-align: left;">Maharashtra</td>
<td style="text-align: left;">Southern Amaanta</td>
<td style="text-align: left;">Salivahana Saka, Jovian cycle (Southern School)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;">Possible Jugma month for kshaya</td>
</tr>
<tr class="odd">
<td>15</td>
<td style="text-align: left;">Orissa</td>
<td style="text-align: left;">Solar</td>
<td style="text-align: left;">Saka, Vilaayati, Aamli, Bengali San</td>
<td style="text-align: left;">Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>16</td>
<td style="text-align: left;">Punjab</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>17</td>
<td style="text-align: left;">Punjab – Nanakshahi</td>
<td style="text-align: left;">Sidereal; fixed relative to Gregorian calendar</td>
<td style="text-align: left;">Nanakshahi</td>
<td style="text-align: left;">14th March</td>
<td style="text-align: left;">Uses traditional names for Punjabi months</td>
</tr>
<tr class="even">
<td>18</td>
<td style="text-align: left;">Rajasthan</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>19</td>
<td style="text-align: left;">Tamil Nadu</td>
<td style="text-align: left;">Solar</td>
<td style="text-align: left;">Kali, Jovian cycle (Southern School)</td>
<td style="text-align: left;">Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>20</td>
<td style="text-align: left;">Tripura</td>
<td style="text-align: left;">Solar</td>
<td style="text-align: left;">Kali, Bengali San</td>
<td style="text-align: left;">Solar Day after Mesha Sankranti</td>
<td style="text-align: left;">Bengali rules for beginning of month</td>
</tr>
<tr class="odd">
<td>21</td>
<td style="text-align: left;">Uttaranchal</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>22</td>
<td style="text-align: left;">Uttar Pradesh</td>
<td style="text-align: left;">Purnimaanta</td>
<td style="text-align: left;">Vikrama Era (Chaitradi)</td>
<td style="text-align: left;">One day after the last new moon before Mesha Sankranti</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>23</td>
<td style="text-align: left;">West Bengal</td>
<td style="text-align: left;">Solar</td>
<td style="text-align: left;">Kali, Bengali San</td>
<td style="text-align: left;">Solar Day after Mesha Sankranti</td>
<td style="text-align: left;">Bengali rules for beginning of month</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Do note that: 1. The table is not exhaustive terms of calendars nor in terms of states. Among others, Arunachal Pradesh, Manipur, Meghalaya, Mizoram, Nagaland and Sikkim were left out. 2. Chatterjee mentions that the Orissa School for deciding the beginning of the solar month is also used in Punjab and Haryana “where the solar calendar is also used”. <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 14</a>)</span></p>
</section>
</section>
<section id="maasa-naamakarana-how-the-months-got-their-names." class="level2">
<h2 class="anchored" data-anchor-id="maasa-naamakarana-how-the-months-got-their-names.">3. <em>Maasa Naamakarana</em>: How the Months got their&nbsp;Names.</h2>
<div class="line-block"><em>Listening to this, she said,</em><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since we are deep in this game,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Might I ask how each month got its name?<br>
<em>To which Apara Ganita stared at a gulmohar flower with twenty-seven buds and replied thus:</em></div>
<p>The complexity of the Indian calendar system is not just in the plethora of calendars available, but also in the manner in which they link up with one another. A principal point of linkage of most Indian calendars is in their names of the months; as we shall see, the similar sets of month names are used in more than one calendar. In this section, we aim to formulate rules determining the naming of the months. Our motivation is not just taxonomic; month names, we shall see, are critical to understanding the Indian calendar system.</p>
<p>We propose that there are two types of month names: -</p>
<section id="months-named-after-nakshatras" class="level3">
<h3 class="anchored" data-anchor-id="months-named-after-nakshatras">3.1 Months named after Nakshatras</h3>
<p>The set of month names named after <em>nakshatras</em> is used by both solar and lunisolar calendars, adding to seeming complexity of the Indian calendar system. Indeed, as we shall see, this type should actually called as ‘Months <em>initially</em> named after <em>Nakshatras</em>’; there has been an infusion of solar rules into an essentially lunar convention.</p>
<p>Let us then, first consider the original rule. Saha and Lahiri mention that pakshas or fortnights were differentiated based on the nakshatra “where the moon is full”.<span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 221</a>)</span> That is to say, if a particular full moon occurs near, say, the lunar asterism, Visakha, the full moon would be called as Vaisakha Purnimaasi, and the month would be Vaisakha. The earliest lunisolar months, then, were purnimaanta, that is, the name of the full moon corresponded to the name of the month. Of course, the full moon occurs at all nakshatras. Fifteen were taken into account for naming of the month, spaced more or less equally.</p>
<p>We thus have the following set of names along with their respective nakshatras<span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 221</a>)</span>:</p>
<div class="cell" data-execution_count="2">
<div id="tbl-nakshatra-months" class="cell quarto-float anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-nakshatra-months-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Nakshtras and Months
</figcaption>
<div aria-describedby="tbl-nakshatra-months-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Nakshatra on Purnima</th>
<th style="text-align: left;">Month Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">Chitra</td>
<td style="text-align: left;">Chaitra</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">Visakha</td>
<td style="text-align: left;">Vaisakha</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">Jyestha</td>
<td style="text-align: left;">Jyaistha</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">(Purva &amp; Uttara) Aashaadha</td>
<td style="text-align: left;">Aashaadha</td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">Sravana</td>
<td style="text-align: left;">Sraavana</td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: left;">(Uttara &amp; Purva) Bhaadrapada</td>
<td style="text-align: left;">Bhaadrapada</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="text-align: left;">Asvini</td>
<td style="text-align: left;">Asvayuja (Aasvina)</td>
</tr>
<tr class="even">
<td>7</td>
<td style="text-align: left;">Krittika</td>
<td style="text-align: left;">Kaarthika</td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: left;">Mrugasira</td>
<td style="text-align: left;">Maarghasira</td>
</tr>
<tr class="even">
<td>9</td>
<td style="text-align: left;">Pushyami</td>
<td style="text-align: left;">Pausa (Pushyam)</td>
</tr>
<tr class="odd">
<td>10</td>
<td style="text-align: left;">Maghaa</td>
<td style="text-align: left;">Maagha</td>
</tr>
<tr class="even">
<td>11</td>
<td style="text-align: left;">(Uttara and Purva) Phalguni</td>
<td style="text-align: left;">Phalguna</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>It may be noted that the months of <em>Aashaadha</em>, <em>Bhadrapada</em> and <em>Phalguna</em> are linked to two <em>nakshatras</em> respectively. Chatterjee and Chakravarthy give the following criteria for choosing <em>nakshatras</em> for month names<span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 281</a>)</span>:</p>
<ol type="1">
<li>The yogataaras or the identifying stars of the nakshatras are prominent or have traditional significance.</li>
<li>They are spaced equidistant from one another.</li>
</ol>
<p>It must be mentioned that this rule is now an approximation largely due to Earth’s precession; for instance, this year’s Chitra Purnimaasi had Swati as its nakshatra. Also, possibly for historical reasons, and allowing for regional variation in pronunciation, the Oriya, Bengali, Assamese, Punjabi and Tamil solar calendars also use the same set of month names.</p>
<p>To reconcile all this, we might frame a new rule, that, the amaanta lunar month takes its number from the solar month that starts in it, but its name from the solar month in which it starts, while following the purnimaanta months in chronological order. That is to say, since Chitra occurred during the purnima of this year’s first purnimaanta month, we call this month as ‘Chaitra’. Consequently, the first amaanta month would also be ‘Chaitra’, which also would be the name of the solar month during which the amaanta ‘Chaitra’ started. However, the ‘number’ of the solar month (‘1’ in the case of amaanta and purnimaanta Chaitra) is not quite the same; the solar Chaitra is the last (i.e., 12th) month of the year. The lunisolar Chaitra’s number is taken by the solar month that begins in it, namely the solar Vaisakha. All this can be seen in the graphic in the next page.</p>
<p>The relationships for all the months may be mapped according to the following table <span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 280</a>)</span> (Punjabi month names <span class="citation" data-cites="purewal">(<a href="#ref-purewal" role="doc-biblioref">Purewal 2002</a>)</span>):</p>
<div class="cell" data-execution_count="3">
<div id="tbl-month-relationships" class="cell quarto-float anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-month-relationships-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Raasis and Months in various parts of India
</figcaption>
<div aria-describedby="tbl-month-relationships-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Raasi</th>
<th style="text-align: left;">Approximate Nakshatra on Purnima</th>
<th style="text-align: left;">Lunar Month Name</th>
<th style="text-align: left;">Solar Month Name</th>
<th style="text-align: left;">Assamese Version</th>
<th style="text-align: left;">Tamil Version</th>
<th style="text-align: left;">Punjabi Version</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">Mesha</td>
<td style="text-align: left;">Chitra</td>
<td style="text-align: left;">Chaitra</td>
<td style="text-align: left;">Vaisakha</td>
<td style="text-align: left;">Bahag</td>
<td style="text-align: left;">Chittarai</td>
<td style="text-align: left;">Vaisakh</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">Vrshava</td>
<td style="text-align: left;">Visakha</td>
<td style="text-align: left;">Vaisakha</td>
<td style="text-align: left;">Jyaishta</td>
<td style="text-align: left;">Jeth</td>
<td style="text-align: left;">Vaikasi</td>
<td style="text-align: left;">Jeth</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">Mithuna</td>
<td style="text-align: left;">Jyestha</td>
<td style="text-align: left;">Jaishta</td>
<td style="text-align: left;">Aashaadha</td>
<td style="text-align: left;">Ahar</td>
<td style="text-align: left;">Aani</td>
<td style="text-align: left;">Harh</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">Karkata</td>
<td style="text-align: left;">(Purva &amp; Uttara) Ashaadha</td>
<td style="text-align: left;">Aashaadha</td>
<td style="text-align: left;">Sraavana</td>
<td style="text-align: left;">Saon</td>
<td style="text-align: left;">Aadi</td>
<td style="text-align: left;">Sawan</td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">Simha</td>
<td style="text-align: left;">Sravana</td>
<td style="text-align: left;">Sraavana</td>
<td style="text-align: left;">Bhaadrapada</td>
<td style="text-align: left;">Bhad</td>
<td style="text-align: left;">Aavani</td>
<td style="text-align: left;">Bhadon</td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: left;">Kanya</td>
<td style="text-align: left;">(Purva &amp; Uttara) Bhaadrapada</td>
<td style="text-align: left;">Bhaadrapada</td>
<td style="text-align: left;">Asvayuja (Aasvina)</td>
<td style="text-align: left;">Ahin</td>
<td style="text-align: left;">Purattaasi</td>
<td style="text-align: left;">Asu</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="text-align: left;">Tula</td>
<td style="text-align: left;">Asvini</td>
<td style="text-align: left;">Asvayuja (Aasvina)</td>
<td style="text-align: left;">Kaarthika</td>
<td style="text-align: left;">Kati</td>
<td style="text-align: left;">Arppisi</td>
<td style="text-align: left;">Katik</td>
</tr>
<tr class="even">
<td>7</td>
<td style="text-align: left;">Vrischika</td>
<td style="text-align: left;">Krittika</td>
<td style="text-align: left;">Kaarthika</td>
<td style="text-align: left;">Maarghasira</td>
<td style="text-align: left;">Aghon</td>
<td style="text-align: left;">Karthigai</td>
<td style="text-align: left;">Maghar</td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: left;">Dhanus</td>
<td style="text-align: left;">Mrugasira</td>
<td style="text-align: left;">Maarghasira</td>
<td style="text-align: left;">Pushyam (Pausa)</td>
<td style="text-align: left;">Puha</td>
<td style="text-align: left;">Maargali</td>
<td style="text-align: left;">Poh</td>
</tr>
<tr class="even">
<td>9</td>
<td style="text-align: left;">Makara</td>
<td style="text-align: left;">Pushyami</td>
<td style="text-align: left;">Pushyam (Pausa)</td>
<td style="text-align: left;">Maagha</td>
<td style="text-align: left;">Magh</td>
<td style="text-align: left;">Thaai</td>
<td style="text-align: left;">Magh</td>
</tr>
<tr class="odd">
<td>10</td>
<td style="text-align: left;">Kumbha</td>
<td style="text-align: left;">Maagha</td>
<td style="text-align: left;">Maagha</td>
<td style="text-align: left;">Phalguna</td>
<td style="text-align: left;">Phagun</td>
<td style="text-align: left;">Maasi</td>
<td style="text-align: left;">Phagun</td>
</tr>
<tr class="even">
<td>11</td>
<td style="text-align: left;">Mina</td>
<td style="text-align: left;">(Uttara &amp; Purva) Phalguni</td>
<td style="text-align: left;">Phalguna</td>
<td style="text-align: left;">Chaitra</td>
<td style="text-align: left;">Chait</td>
<td style="text-align: left;">Panguni</td>
<td style="text-align: left;">Chet</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The Assamese, Punjabi and Tamil versions have been provided to give an idea of the linguistic variation. It is also interesting to observe that the National Calendar suggested by Saha and Lahiri also uses the same set of month names, increasing the potential confusion. As is probably obvious by now, the rule does not correspond to the Tamil, National and Nanakshahi calendars.</p>
</section>
<section id="months-named-after-raasis" class="level3">
<h3 class="anchored" data-anchor-id="months-named-after-raasis">3.2 Months named after Raasis</h3>
<p>Only solar months share their names with <em>raasis</em>. SK Chatterjee and Apurba Kumar Chakravarthy give the following names along with the associated <em>raasis</em><span class="citation" data-cites="chakravarty1985indian">(<a href="#ref-chakravarty1985indian" role="doc-biblioref">Chakravarty and Chatterjee 1985, 280</a>)</span>:</p>
<div class="cell" data-execution_count="4">
<div id="tbl-raasi-months" class="cell quarto-float anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-raasi-months-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Malayalam months named after <em>raasis</em>
</figcaption>
<div aria-describedby="tbl-raasi-months-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Raasi</th>
<th style="text-align: left;">Sanskritised Version</th>
<th style="text-align: left;">Malayalam Version</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">Mesha</td>
<td style="text-align: left;">Mesha</td>
<td style="text-align: left;">Medam</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">Vrshava</td>
<td style="text-align: left;">Vrshava</td>
<td style="text-align: left;">Edavam</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">Mithuna</td>
<td style="text-align: left;">Mithuna</td>
<td style="text-align: left;">Midhunam</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">Karkata</td>
<td style="text-align: left;">Karkata</td>
<td style="text-align: left;">Karitaka</td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">Simha</td>
<td style="text-align: left;">Simha</td>
<td style="text-align: left;">Chingam</td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: left;">Kanya</td>
<td style="text-align: left;">Kanya</td>
<td style="text-align: left;">Kanni</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="text-align: left;">Tula</td>
<td style="text-align: left;">Tula</td>
<td style="text-align: left;">Thulam</td>
</tr>
<tr class="even">
<td>7</td>
<td style="text-align: left;">Vrischika</td>
<td style="text-align: left;">Vrischika</td>
<td style="text-align: left;">Vrischikam</td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: left;">Dhanus</td>
<td style="text-align: left;">Dhanus</td>
<td style="text-align: left;">Dhanu</td>
</tr>
<tr class="even">
<td>9</td>
<td style="text-align: left;">Makara</td>
<td style="text-align: left;">Makara</td>
<td style="text-align: left;">Makaram</td>
</tr>
<tr class="odd">
<td>10</td>
<td style="text-align: left;">Kumbha</td>
<td style="text-align: left;">Kumbha</td>
<td style="text-align: left;">Kumbham</td>
</tr>
<tr class="even">
<td>11</td>
<td style="text-align: left;">Mina</td>
<td style="text-align: left;">Mina</td>
<td style="text-align: left;">Minam</td>
</tr>
<tr class="odd">
<td>12</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>That is to say, the month shares its name with that of its corresponding <em>Sankranti</em>. For instance, if <em>Mesha Sankranti</em> occurs on a certain day, then the period until the next <em>Sankranti</em> would be <em>Mesha maasa (Medham maasam)</em>.</p>
<p>This naming rule is followed primarily in the Malayalam calendar. Incidentally, Abhayankar says that the Oriya calendar also follows this rule. <span class="citation" data-cites="abhayankar1993debts">(<a href="#ref-abhayankar1993debts" role="doc-biblioref">Abhayankar 1993, 55</a>)</span></p>
</section>
</section>
<section id="parva-dina-nirnaya-how-the-days-of-festivals-are-decided." class="level2">
<h2 class="anchored" data-anchor-id="parva-dina-nirnaya-how-the-days-of-festivals-are-decided.">4. <em>Parva Dina&nbsp;Nirnaya</em>: How the days of festivals are&nbsp;decided.</h2>
<div class="line-block"><em>Hearing him speak, she asked,</em><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The cultural complexity is interesting,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;but perhaps you have a festivals listing?<br>
<em>To which Apara Ganita looked at birds chirping and replied thus:</em></div>
<p>We provide a list of Indian festivals, along with their (Indic) dates and the calendar used to reckon the particular festival. The list of festivals is by no means exhaustive; the entries are mostly public holidays in India.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-indian-festivals" class="cell quarto-float anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-indian-festivals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Various Indic Festivals <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 60–68</a>)</span>
</figcaption>
<div aria-describedby="tbl-indian-festivals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Festival</th>
<th style="text-align: left;">Indic Date</th>
<th style="text-align: left;">Additional Rules</th>
<th style="text-align: left;">Calendar Used</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">Makara Sankranti/ Pongal</td>
<td style="text-align: left;">Makara Sankranti</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Solar</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">Maha Siva Raatri</td>
<td style="text-align: left;">Magha K 14</td>
<td style="text-align: left;">Must cover a nisita</td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">Holi</td>
<td style="text-align: left;">Phalguna Purnima</td>
<td style="text-align: left;">Holika Dahana is observed on the night of the Purnima; Holi is observed on the solar day after Holika Dahana.</td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">Ugadi / Gudi Padwa</td>
<td style="text-align: left;">Chaitra S 1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">Rama Navami</td>
<td style="text-align: left;">Chaitra S 9</td>
<td style="text-align: left;">Must cover Madyahna</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: left;">Tamil New Year, Vishu, Bengali New Year</td>
<td style="text-align: left;">Mesha Sankranti</td>
<td style="text-align: left;">Respective Sankranti rules</td>
<td style="text-align: left;">Solar</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="text-align: left;">Ganesh Chaturti</td>
<td style="text-align: left;">Bhadrapada S 4</td>
<td style="text-align: left;">Must cover Madyahna</td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="even">
<td>7</td>
<td style="text-align: left;">Buddha Purnima</td>
<td style="text-align: left;">Vaisakhi Purnima</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: left;">Raksha Bandan</td>
<td style="text-align: left;">Sravana Purnima</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="even">
<td>9</td>
<td style="text-align: left;">Janmashtami</td>
<td style="text-align: left;">Sravana K 8</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="odd">
<td>10</td>
<td style="text-align: left;">Onam</td>
<td style="text-align: left;">Moon is in Sravana nakshatra in Solar Bhadrapada</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Lunisolar and Solar</td>
</tr>
<tr class="even">
<td>11</td>
<td style="text-align: left;">Mahanavami <span class="citation" data-cites="sarma2002interview">(<a href="#ref-sarma2002interview" role="doc-biblioref">Sivasri Sarma 2002</a>)</span></td>
<td style="text-align: left;">Asvayuja S 9</td>
<td style="text-align: left;">(Mahanavami is reckoned before the other 8 days of Dussehra)</td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="odd">
<td>12</td>
<td style="text-align: left;">Vijayadasami <span class="citation" data-cites="sarma2002interview">(<a href="#ref-sarma2002interview" role="doc-biblioref">Sivasri Sarma 2002</a>)</span></td>
<td style="text-align: left;">(The thithi after Mahanavami)</td>
<td style="text-align: left;">Must cover a Nisita</td>
<td style="text-align: left;">Lunisolar</td>
</tr>
<tr class="even">
<td>13</td>
<td style="text-align: left;">Deepavali</td>
<td style="text-align: left;">Asvayuja Amavasya</td>
<td style="text-align: left;">Must cover pradosha</td>
<td style="text-align: left;">Lunisolar</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A bit of explanation is necessary. First, the terms. “<em>Nisita</em>” is defined to be a time- period measured by two <em>ghatikas</em> (1/60th of a solar day; approximately 20 minutes) stretching on either side of midnight. “<em>Pradosha</em>” is the time-period stretching for two <em>muhurtas</em> (1/15th of the time between sunrise and sunset; approximately 1 hour 36 minutes) after sunset. “<em>Madhyahna</em>” is one-third of the time-period between sunrise and sunset. This fraction covers mid-day.</p>
<p>Second, these dates are valid only on non-intercalary <em>thithis</em> for all lunisolar festivals. Both leap days and non-leap days in leap months are deemed unfit for festivals. (<em>Kshaya maasas</em> are not an issue here because a) <em>jugma</em> months are deemed fit for religious observance and b) in the Eastern and Northwestern schools, the extra intercalary month is deemed to be normal).</p>
<p>And finally, if the given <em>thithi</em> doesn’t cover the given time, or covers the given time on two solar days, then the second solar day is reckoned to be the respective festival.</p>
</section>
<section id="samvad-sandesha-how-eras-come-into-play" class="level2">
<h2 class="anchored" data-anchor-id="samvad-sandesha-how-eras-come-into-play">5. <em>Samvad Sandesha</em>: How Eras come into play</h2>
<div class="line-block"><em>Perceiving the response, she questioned:</em><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I do not know if this is an important part,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;but from when do all calendars start?<br>
<em>To which Apara Ganita looked at a foundation stone and replied thus:</em></div>
<p>The Indian calendar system follows a wide range of eras, some of historical interest. Also, we do not attempt to link individual calendars to eras, for the same calendar may be reckoned with two different eras in two different places.</p>
<p>Here’s the listing:</p>
<div class="cell" data-execution_count="6">
<div id="tbl-indian-eras" class="cell quarto-float anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-indian-eras-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Various Indic Eras <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 252–58</a>)</span>
</figcaption>
<div aria-describedby="tbl-indian-eras-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Era</th>
<th style="text-align: left;">Zero Year</th>
<th style="text-align: left;">Beginning of Era with respect to individual year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">Saka</td>
<td style="text-align: left;">78 CE</td>
<td style="text-align: left;">Mesha Sankranti, Chaitra S 1</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">Vikrama</td>
<td style="text-align: left;">57 CE</td>
<td style="text-align: left;">Mesha Sankranti, Chaitra S 1, Karthika S 1, Ashadha S 1</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">Kali</td>
<td style="text-align: left;">3101 BCE</td>
<td style="text-align: left;">Mesha Sankranti, Chaitra S 1</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">Kollam</td>
<td style="text-align: left;">824 CE</td>
<td style="text-align: left;">Kanya Sankranti, Simha Sankranti</td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">Bengali San</td>
<td style="text-align: left;">963 + solar years since 1556 CE</td>
<td style="text-align: left;">Mesha Sankranti</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In addition, some regions also name their years according to the names of the Jovian years. Saha and Lahiri point out that there are two schools for this; the Southern school names its years in continuous succession, while the Northern school names its years corresponding to the present Jovian year. <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 272</a>)</span></p>
</section>
<section id="kshaya-sutra-how-certain-months-are-dropped" class="level2">
<h2 class="anchored" data-anchor-id="kshaya-sutra-how-certain-months-are-dropped">6. <em>Kshaya Sutra</em>: How certain months are&nbsp;dropped</h2>
<div class="line-block"><em>Observing the reaction, she enquired:</em><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To calendars you seem an active saakshya <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;but from when do all calendars start?<br>
<em>To which, Apara Ganita looked at some fallen leaves and replied thus:</em></div>
<p>One of the most interesting aspects of the Indian lunisolar calendar is its <em>kshaya maasas</em>, literally “decayed months”. Occasionally, certain months are dropped from the lunisolar calendar. We now try to understand the modalities behind this omission; we try to answer how, why, when and where it happens.</p>
<p>First, let us try to define a kshaya month. Chatterjee, in his work on Indian calendars, says that a certain lunar month “may completely overlap any of the short three nirayana solar months of Margasira, Pausha and Magha”, with the result that there will be no new moon in the respective solar month. Consequently, there will be no lunar month named “after […] this solar month”. <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 34</a>)</span> This interaction may be visualized in <a href="#fig-kalachakra" class="quarto-xref">Figure&nbsp;1</a>.</p>
<p>We learn the following from this statement:  1. That the solar months of Margasira, Pausa and Magha are small, 2. That at a certain time, there might be no new moon in these months, and 3. The corresponding lunar month is dropped from the calendar.</p>
<p>Note that Chatterjee is silent on whether the dropped lunar month is amaanta or purnimaanta; a naïve assumption would be that since he talks about new moons, the month would be amaanta. But a study of the (Chaitradi) amaanta and purnimaanta calendars for the present year reveals that the difference between these two calendars is still two weeks. Therefore, it’s safe to conclude that kshaya months were dropped from the purnimaanta calendar as well.</p>
<p>Moreover, the statement about “corresponding lunar month” is unclear; are we talking about the lunar month with the same number as the new-moon-lacking solar month? Or are we talking about the lunar month with the same name of the solar month? Running the <em>calendrica</em> code provided by Dershowitz and Reingold with their book <em>Calendrical Calculations - The Millenium Edition</em> (see table for values), we see that it is the lunar month with the same name that gets dropped.</p>
<p>To account for a purnimaanta kshaya, and to further clarify which month to drop, we re-phrase the definition of a kshaya month to be thus:</p>
<blockquote class="blockquote">
<p>“In any given lunar year, if two consecutive Sankrantis occur between two consecutive new moons, then the lunar month, whether amaanta or purnimaanta, with the same name as the solar month in which this occurs, is dropped.”</p>
</blockquote>
<p>As we shall see, such a re-phrasing is useful for computational purposes.</p>
<p>Indeed, as we mentioned earlier, we ran the Dershowitz and Reingold’s calendrica package to get values for the occurrence of a kshaya month. Since searching for a kshaya month is computationally very heavy<span class="citation" data-cites="deshowitz2002calendar">(<a href="#ref-deshowitz2002calendar" role="doc-biblioref">Dershowitz and Reingold 2002, 24</a>)</span>, we used a table prepared by Saha and Lahiri (table 22 in the book)<span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 250</a>)</span> as a starting point. We also tabulated results for non- kshaya months, specifically years with gaps of 19, 46, 65, 76, 122 and 141 years respectively. The results and the graphs from these results are tabulated in <a href="#tbl-kshaya-timings" class="quarto-xref">Table&nbsp;8</a>.</p>
<p>It must be noted that all cases tabulated previously have been calculated according to Surya Siddhantic rules and that we may get a different set of results if calculated according to ephemeris calculations. Indeed, as Chatterjee has pointed out, there was a difference in 1964 CE; ephemeris calculations showed Margasira to be kshaya (and Karthika, Chaitra to be adhika), while as we’ve seen, Surya Siddhantic computation showed Pausa to be kshaya (and Asvina and Chaitra to be adhika) <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 38</a>)</span> Chatterjee, however, seems to be in agreement with Dershowitz and Reingold in saying that there was a kshaya in Magha in 1983 CE <span class="citation" data-cites="deshowitz2001calendrical">(<a href="#ref-deshowitz2001calendrical" role="doc-biblioref">Deshowitz and Reingold 2001, 269</a>)</span>, despite his use of ephemeris calculations.</p>
<p>What do we get from all this? We see that a kshaya month can occur every 19, 46, 65, 76, 122 or 141 years. Indeed, Saha and Lahiri’s tabulation provide us with the following frequencies of occurrences for gaps between kshaya months <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 250</a>)</span>:</p>
<div id="tbl-kshaya-gap" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kshaya-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Number of times a particular interval gap occurred
</figcaption>
<div aria-describedby="tbl-kshaya-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th>Interval</th>
<th>Number of times occuring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19</td>
<td>11</td>
</tr>
<tr class="even">
<td>46</td>
<td>3</td>
</tr>
<tr class="odd">
<td>65</td>
<td>1</td>
</tr>
<tr class="even">
<td>76</td>
<td>1</td>
</tr>
<tr class="odd">
<td>122</td>
<td>1</td>
</tr>
<tr class="even">
<td>141</td>
<td>6</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We therefore see that between 525 CE and 1985 CE, kshaya occurred 11 times with a gap of 19 years, thrice with a gap of 46 years, six times with a gap of 141 years, and once each with gaps of 65, 76 and 122 years. The obvious question one would like to ask would be why. Why does kshaya occur only in these gaps?</p>
<p>To answer this better, we re-iterate what causes kshaya in the first place. We already said that a kshaya would occur when two consecutive Sankrantis occur between two Amavasyas. That is to say, when a solar month is shorter in length than, and is completely enclosed by, a (an Amaanta) lunar month. Saha and Lahiri go on to say that the “maximum duration of a lunar month exceeds the lengths of the solar months only in the case of Margasira, Pausa and Magha” <span class="citation" data-cites="saha1992report">(<a href="#ref-saha1992report" role="doc-biblioref">Saha and Lahiri 1992, 250</a>)</span> and that, therefore, kshaya is possible only in these months.</p>
<p>This would explain the solar month part, but what of lunar? How can the lunar month be bigger than the solar month? Ala’a Juwad has some answers; in his article, he suggests that the canonical synodic month, a lunar month between two consecutive phases of the moon, is not constant in length. Indeed, he goes on to say that between 1600 and 2400 CE, the synodic month extends in length from 29 days 6 hours and 31 minutes to 29 days 19 hours and 59 minutes. <span class="citation" data-cites="jawad1993long">(<a href="#ref-jawad1993long" role="doc-biblioref">Jawad 1993, 76</a>)</span> Moreover, he says that the “longest lunar months&nbsp;… occur when the date of the new Moon coincides with apogee”.<span class="citation" data-cites="jawad1993long">(<a href="#ref-jawad1993long" role="doc-biblioref">Jawad 1993, 76</a>)</span> A brute-force search for the longest synodic month definitely won’t give us a kshaya; for kshaya to occur, the lunar month needs to be only bigger than its solar counterpart and more importantly, completely encompass it. Indeed, Jawad says that the longest synodic month occurred in 1610 CE, a year which occurs within the 141 year long kshaya hiatus between 1540–1541 CE and 1680–81 CE.</p>
<p>We therefore search for other clues to unscramble kshaya. On a purely arithmetic perspective, we observe the following: -</p>
<pre><code>19 = 19 * 1
46 = 19 * 2 + 8
65 = 19 * 3 + 8
76 = 19 * 4
122 = 19 * 6 + 8
141 = 19 * 7 + 8</code></pre>
<p>Is it possible then, that the kshaya month has something to do with the Metonic cycle? The Metonic Cycle is a fairly well documented phenomenon; first observed by the Greek astronomer Metos, every 19 years, the lunar dates overlap with the tropical ones. The underlying mathematical reason is simple: 19 sidereal years contain <code>19*365.242189 = 6939.6</code> solar days, while 235 synodic months (with a mean of 29.53 solar days) contain <code>235*29.530588853 = 6939.68</code> solar days. The lengths overlap. But this obviously is neither necessary nor sufficient; it might be useful for the dates to repeat, but it definitely does not fulfil the requirement for kshaya.</p>
<p>One suggestion therefore, might be that the kshaya occurs when the number of solar days of a sidereal year is equal to that of a synodic month, which in turn is equal to that from an anomalistic month. An anomalistic month is defined to be the time - period between two consecutive perigee passages and has a mean value of 27.55455 days. Taking these average values, we calculate the average values of solar days in whole numbers of synodic and anomalistic months: -</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Interval</th>
<th>Occurrence</th>
<th>Modulo</th>
<th>Solar Year</th>
<th>Synodic Months</th>
<th>Anomalistic Months</th>
<th>Canonical Kshaya Year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19</td>
<td>11</td>
<td>1*19</td>
<td>6939.601591</td>
<td>6939.68838</td>
<td>6943.7466</td>
<td>Kshaya</td>
</tr>
<tr class="even">
<td>27</td>
<td>0</td>
<td>1*19+8</td>
<td>9861.539103</td>
<td>9863.216677</td>
<td>9864.5289</td>
<td></td>
</tr>
<tr class="odd">
<td>38</td>
<td>0</td>
<td>2*19</td>
<td>13879.20318</td>
<td>13879.37676</td>
<td>13887.4932</td>
<td></td>
</tr>
<tr class="even">
<td>46</td>
<td>3</td>
<td>2*19+8</td>
<td>16801.14069</td>
<td>16802.90506</td>
<td>16808.2755</td>
<td>Kshaya</td>
</tr>
<tr class="odd">
<td>57</td>
<td>0</td>
<td>3*19</td>
<td>20818.80477</td>
<td>20819.06514</td>
<td>20831.2398</td>
<td></td>
</tr>
<tr class="even">
<td>65</td>
<td>1</td>
<td>3*19+8</td>
<td>23740.74229</td>
<td>23742.59344</td>
<td>23752.0221</td>
<td>Kshaya</td>
</tr>
<tr class="odd">
<td>76</td>
<td>1</td>
<td>4*19</td>
<td>27758.40636</td>
<td>27758.75352</td>
<td>27774.9864</td>
<td>Kshaya</td>
</tr>
<tr class="even">
<td>84</td>
<td>0</td>
<td>4*19+8</td>
<td>30680.34388</td>
<td>30682.28182</td>
<td>30695.7687</td>
<td></td>
</tr>
<tr class="odd">
<td>95</td>
<td>0</td>
<td>5*19</td>
<td>34698.00796</td>
<td>34698.4419</td>
<td>34718.733</td>
<td></td>
</tr>
<tr class="even">
<td>103</td>
<td>0</td>
<td>5*19+8</td>
<td>37619.94547</td>
<td>37621.9702</td>
<td>37639.5153</td>
<td></td>
</tr>
<tr class="odd">
<td>114</td>
<td>0</td>
<td>6*19</td>
<td>41637.60955</td>
<td>41638.13028</td>
<td>41634.92505</td>
<td></td>
</tr>
<tr class="even">
<td>122</td>
<td>1</td>
<td>6*19+8</td>
<td>44559.54706</td>
<td>44561.65858</td>
<td>44555.70735</td>
<td>Kshaya</td>
</tr>
<tr class="odd">
<td>133</td>
<td>0</td>
<td>7*19</td>
<td>48577.21114</td>
<td>48577.81866</td>
<td>48578.67165</td>
<td></td>
</tr>
<tr class="even">
<td>141</td>
<td>6</td>
<td>7*19+8</td>
<td>51499.14865</td>
<td>51501.34696</td>
<td>51499.45395</td>
<td>Kshaya</td>
</tr>
</tbody>
</table>
<p>Broadly speaking, we might summarize the above table as thus: - for the most part, the number of solar days in solar years, synodic and anomalistic months overlap in kshaya years. However, this overlap doesn’t occur only in kshaya years; as the table shows, there’s an overlap for 133 years as well. Does this, then, explain the kshaya phenomenon? We might summarize it as being strongly suggestive, but definitely not conclusive.</p>
<section id="treatment-of-kshaya-months" class="level3">
<h3 class="anchored" data-anchor-id="treatment-of-kshaya-months">6.1 Treatment of Kshaya Months</h3>
<p>We may complete our discussion of kshaya months by describing the three Kshaya Schools of thought. <span class="citation" data-cites="chatterjee1988indian">(<a href="#ref-chatterjee1988indian" role="doc-biblioref">Chatterjee 1988, 37–40</a>)</span></p>
<p>The <em>North Western School</em> is followed in the north-western part of the country, presumably in Gujarat and/ or Rajasthan, where the lunisolar calendar is used. Essentially, the North Western School treats the adhika month before kshaya as a normal month and the one after the kshaya month to be intercalary.</p>
<p>This contrasts with the <em>Eastern School</em> where the reverse is followed; the adhika month before the kshaya is deemed intercalary, while the one after it is deemed normal. The Eastern School is followed in the eastern parts of the country, where the lunisolar calendar is followed.</p>
<p>The final of the trio, the <em>Southern School</em>, treats both adhika maasas as intercalary, instead reckoning the kshaya month as a “jugma”, i.e., the first half of the thithi of this month is deemed to be that of the first month, and the second half as that of the second month. This is presumably followed in the Southern parts of the country where the lunisolar calendar is followed.</p>
</section>
</section>
<section id="epilogue" class="level2">
<h2 class="anchored" data-anchor-id="epilogue">7. Epilogue</h2>
<p><em>By this time, onlookers all sides gathered around the two. They were attentively listening to the conversation between them. Along with Apara Ganita, they were waiting for the dwara palika to ask once again. But she didn’t. She stood and smiled. Her face was radiant, glowing like the moon on a Purnima and the harsh summer sun entering the Mithuna raasi.</em></p>
<p><em>She still said nothing. She got up and walked away from the crowd. Still smiling. Still graceful.</em></p>
<p><em>The sparks came slowly, but suddenly. All around them, the landscape was changing. The gate was melting into the walls, the walls into the ground. The ground was changing into grass, the grass covering the entire ground.</em></p>
<p><em>Except the ground underneath Apara Ganita. He found himself standing on an elevated podium, facing listeners all around him, all waiting to hear him speak.</em></p>
<p><em>For once, he didn’t know what to say.</em></p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">8. References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-abhayankar1993debts" class="csl-entry" role="listitem">
Abhayankar, KD. 1993. <span>“Our Debts to Our Ancestors.”</span> In <em>Treasures of Ancient Indian Astronomy</em>, edited by KD Abhayankar and Dr. BG Sidharth. Ajanta Publications, Delhi.
</div>
<div id="ref-chakravarty1985indian" class="csl-entry" role="listitem">
Chakravarty, Apurba Kumar, and SK Chatterjee. 1985. <span>“Indian Calendar from Post-Vedic Period to AD 1900.”</span> In <em>History of Astronomy in India</em>. Indian National Science Academy.
</div>
<div id="ref-chatterjee1988indian" class="csl-entry" role="listitem">
Chatterjee, SK. 1988. <em>Indian Calendric System</em>. Publications Division, Ministry of Information; Broadcasting, Government of India.
</div>
<div id="ref-deshowitz2002calendar" class="csl-entry" role="listitem">
Dershowitz, Nachum, and Reingold. 2002. <em>Calendar Tabulations - 1900 to 2200</em>. Cambridge University Press.
</div>
<div id="ref-deshowitz2001calendrical" class="csl-entry" role="listitem">
Deshowitz, Nachum, and Edward M Reingold. 2001. <em>Calendrical Computations: The Millennium Edition</em>. Cambridge Univeristy Press, Cambridge.
</div>
<div id="ref-jawad1993long" class="csl-entry" role="listitem">
Jawad, Ala’a H. 1993. <span>“How Long Is a Lunar Month?”</span> <em>Sky and Telescope</em>.
</div>
<div id="ref-purewal" class="csl-entry" role="listitem">
Purewal, Pal Singh. 2002. <span>“Nanakshahi Samat.”</span> 2002. <a href="http://www.sikh.net/sikhism/Nanakshahi.htm">http://www.sikh.net/sikhism/Nanakshahi.htm</a>.
</div>
<div id="ref-saha1992report" class="csl-entry" role="listitem">
Saha, MH, and NC Lahiri. 1992. <em>Report of the Calendar Reform Committee</em>. Council of Scientific; Industrial Research, New Delhi.
</div>
<div id="ref-sarma2002interview" class="csl-entry" role="listitem">
Sivasri Sarma, Madugula. 2002. <span>“Interview by Author.”</span> Hyderabad, India.
</div>
<div id="ref-simonfraser" class="csl-entry" role="listitem">
University, Simon Fraser. 2002. <span>“Bhaskaracharya.”</span> 2002. <a href="http://www.math.sfu.ca/histmath/India/12thCenturyAD/Bhaskara.html">http://www.math.sfu.ca/histmath/India/12thCenturyAD/Bhaskara.html</a>.
</div>
</div>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">9. Appendix</h2>
<div class="cell" data-execution_count="8">
<div id="tbl-kshaya-timings" class="cell quarto-float anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kshaya-timings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Sankranti and Amavasya timings from Margasira, Pausa, Magha and Phalguna for various years.
</figcaption>
<div aria-describedby="tbl-kshaya-timings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="8">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Indic Solar (Saka Era)</th>
<th style="text-align: left;">Gregorian (CE)</th>
<th style="text-align: left;">Indic Lunar (Vikrama Era)</th>
<th style="text-align: left;">Leap Month?</th>
<th style="text-align: left;">Leap Day?</th>
<th style="text-align: left;">Sankranti</th>
<th style="text-align: left;">Amavasya</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td style="text-align: left;">1237/8/1</td>
<td style="text-align: left;">1315/11/6</td>
<td style="text-align: left;">1372/8/1</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">07:50:07.603</td>
<td style="text-align: left;">05:47:04.872</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">1237/9/1</td>
<td style="text-align: left;">1315/12/5</td>
<td style="text-align: left;">1372/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">19:36:46.043</td>
<td style="text-align: left;">19:48:11.479</td>
</tr>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">1256/9/1</td>
<td style="text-align: left;">1334/12/5</td>
<td style="text-align: left;">1391/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">17:36:21.429</td>
<td style="text-align: left;">11:17:01.381</td>
</tr>
<tr class="even">
<td>3</td>
<td style="text-align: left;">1256/10/1</td>
<td style="text-align: left;">1335/1/3</td>
<td style="text-align: left;">1391/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">01:14:16.038</td>
<td style="text-align: left;">03:48:04.528</td>
</tr>
<tr class="odd">
<td>4</td>
<td style="text-align: left;">1302/8/1</td>
<td style="text-align: left;">1380/11/5</td>
<td style="text-align: left;">1437/8/30</td>
<td style="text-align: left;">True</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">03:29:37.170</td>
<td style="text-align: left;">02:34:46.447</td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: left;">1302/9/1</td>
<td style="text-align: left;">1380/12/5</td>
<td style="text-align: left;">1437/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">15:16:26.115</td>
<td style="text-align: left;">21:15:12.204</td>
</tr>
<tr class="odd">
<td>6</td>
<td style="text-align: left;">1321/9/1</td>
<td style="text-align: left;">1399/12/6</td>
<td style="text-align: left;">1456/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">13:16:01.519</td>
<td style="text-align: left;">07:32:11.950</td>
</tr>
<tr class="even">
<td>7</td>
<td style="text-align: left;">1321/10/1</td>
<td style="text-align: left;">1400/1/4</td>
<td style="text-align: left;">1456/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">20:53:56.115</td>
<td style="text-align: left;">00:39:59.510</td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: left;">1397/10/1</td>
<td style="text-align: left;">1476/1/6</td>
<td style="text-align: left;">1532/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">12:52:28.218</td>
<td style="text-align: left;">11:39:20.696</td>
</tr>
<tr class="even">
<td>9</td>
<td style="text-align: left;">1397/11/1</td>
<td style="text-align: left;">1476/2/4</td>
<td style="text-align: left;">1532/10/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">23:36:42.517</td>
<td style="text-align: left;">00:05:00.597</td>
</tr>
<tr class="odd">
<td>10</td>
<td style="text-align: left;">1443/8/1</td>
<td style="text-align: left;">1521/11/9</td>
<td style="text-align: left;">1578/8/30</td>
<td style="text-align: left;">True</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">15:07:49.331</td>
<td style="text-align: left;">14:22:17.756</td>
</tr>
<tr class="even">
<td>11</td>
<td style="text-align: left;">1443/9/1</td>
<td style="text-align: left;">1521/12/8</td>
<td style="text-align: left;">1578/8/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">True</td>
<td style="text-align: left;">02:54:38.328</td>
<td style="text-align: left;">09:59:51.334</td>
</tr>
<tr class="odd">
<td>12</td>
<td style="text-align: left;">1462/9/1</td>
<td style="text-align: left;">1540/12/8</td>
<td style="text-align: left;">1597/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">00:54:13.716</td>
<td style="text-align: left;">17:36:31.986</td>
</tr>
<tr class="even">
<td>13</td>
<td style="text-align: left;">1462/10/1</td>
<td style="text-align: left;">1541/1/7</td>
<td style="text-align: left;">1597/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">08:32:08.341</td>
<td style="text-align: left;">12:29:37.136</td>
</tr>
<tr class="odd">
<td>14</td>
<td style="text-align: left;">1603/9/1</td>
<td style="text-align: left;">1681/12/10</td>
<td style="text-align: left;">1738/9/1</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">12:32:25.884</td>
<td style="text-align: left;">05:14:33.480</td>
</tr>
<tr class="even">
<td>15</td>
<td style="text-align: left;">1603/10/1</td>
<td style="text-align: left;">1682/1/8</td>
<td style="text-align: left;">1738/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">20:10:20.531</td>
<td style="text-align: left;">01:11:37.994</td>
</tr>
<tr class="odd">
<td>16</td>
<td style="text-align: left;">1744/9/1</td>
<td style="text-align: left;">1822/12/13</td>
<td style="text-align: left;">1879/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">00:10:27.526</td>
<td style="text-align: left;">17:52:00.161</td>
</tr>
<tr class="even">
<td>17</td>
<td style="text-align: left;">1744/9/1</td>
<td style="text-align: left;">1822/12/13</td>
<td style="text-align: left;">1879/8/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">00:10:27.526</td>
<td style="text-align: left;">17:52:00.161</td>
</tr>
<tr class="odd">
<td>18</td>
<td style="text-align: left;">1744/10/1</td>
<td style="text-align: left;">1823/1/12</td>
<td style="text-align: left;">1879/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">07:48:32.677</td>
<td style="text-align: left;">13:46:57.632</td>
</tr>
<tr class="even">
<td>19</td>
<td style="text-align: left;">1744/10/1</td>
<td style="text-align: left;">1823/1/12</td>
<td style="text-align: left;">1879/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">07:48:32.677</td>
<td style="text-align: left;">13:46:57.632</td>
</tr>
<tr class="odd">
<td>20</td>
<td style="text-align: left;">1763/9/1</td>
<td style="text-align: left;">1841/12/13</td>
<td style="text-align: left;">1898/9/1</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">22:10:02.920</td>
<td style="text-align: left;">02:02:04.954</td>
</tr>
<tr class="even">
<td>21</td>
<td style="text-align: left;">1763/10/1</td>
<td style="text-align: left;">1842/1/11</td>
<td style="text-align: left;">1898/9/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">05:48:08.110</td>
<td style="text-align: left;">20:30:22.804</td>
</tr>
<tr class="odd">
<td>22</td>
<td style="text-align: left;">1763/11/1</td>
<td style="text-align: left;">1842/2/10</td>
<td style="text-align: left;">1898/10/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">16:32:11.852</td>
<td style="text-align: left;">16:06:10.978</td>
</tr>
<tr class="even">
<td>23</td>
<td style="text-align: left;">1763/12/1</td>
<td style="text-align: left;">1842/3/12</td>
<td style="text-align: left;">1898/11/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">12:14:30.094</td>
<td style="text-align: left;">10:53:27.932</td>
</tr>
<tr class="odd">
<td>24</td>
<td style="text-align: left;">1790/9/1</td>
<td style="text-align: left;">1868/12/13</td>
<td style="text-align: left;">1925/09/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">21:50:32.239</td>
<td style="text-align: left;">06:09:24.227</td>
</tr>
<tr class="even">
<td>25</td>
<td style="text-align: left;">1790/10/1</td>
<td style="text-align: left;">1869/1/11</td>
<td style="text-align: left;">1925/10/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">05:28:37.402</td>
<td style="text-align: left;">23:17:43.494</td>
</tr>
<tr class="odd">
<td>26</td>
<td style="text-align: left;">1790/11/1</td>
<td style="text-align: left;">1869/2/10</td>
<td style="text-align: left;">1925/11/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">16:12:41.144</td>
<td style="text-align: left;">18:05:11.108</td>
</tr>
<tr class="even">
<td>27</td>
<td style="text-align: left;">1790/12/1</td>
<td style="text-align: left;">1869/3/12</td>
<td style="text-align: left;">1925/12/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">11:54:48.881</td>
<td style="text-align: left;">13:00:01.825</td>
</tr>
<tr class="odd">
<td>28</td>
<td style="text-align: left;">1809/9/1</td>
<td style="text-align: left;">1887/12/14</td>
<td style="text-align: left;">1944/09/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">19:50:18.190</td>
<td style="text-align: left;">00:36:07.304</td>
</tr>
<tr class="even">
<td>29</td>
<td style="text-align: left;">1809/10/1</td>
<td style="text-align: left;">1888/1/12</td>
<td style="text-align: left;">1944/10/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">03:28:12.797</td>
<td style="text-align: left;">13:35:00.591</td>
</tr>
<tr class="odd">
<td>30</td>
<td style="text-align: left;">1809/11/1</td>
<td style="text-align: left;">1888/2/11</td>
<td style="text-align: left;">1944/11/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">14:12:16.539</td>
<td style="text-align: left;">04:16:12.013</td>
</tr>
<tr class="even">
<td>31</td>
<td style="text-align: left;">1809/12/1</td>
<td style="text-align: left;">1888/3/12</td>
<td style="text-align: left;">1944/12/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">09:54:34.781</td>
<td style="text-align: left;">20:22:28.399</td>
</tr>
<tr class="odd">
<td>32</td>
<td style="text-align: left;">1820/9/1</td>
<td style="text-align: left;">1898/12/14</td>
<td style="text-align: left;">1955/09/01</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">19:50:18.190</td>
<td style="text-align: left;">00:36:07.304</td>
</tr>
<tr class="even">
<td>33</td>
<td style="text-align: left;">1820/10/1</td>
<td style="text-align: left;">1899/1/12</td>
<td style="text-align: left;">1955/10/01</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">23:46:54.268</td>
<td style="text-align: left;">04:05:28.667</td>
</tr>
<tr class="odd">
<td>34</td>
<td style="text-align: left;">1820/11/1</td>
<td style="text-align: left;">1899/2/11</td>
<td style="text-align: left;">1955/11/01</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">10:31:08.567</td>
<td style="text-align: left;">14:31:57.701</td>
</tr>
<tr class="even">
<td>35</td>
<td style="text-align: left;">1820/12/1</td>
<td style="text-align: left;">1899/3/12</td>
<td style="text-align: left;">1955/12/01</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">06:13:16.303</td>
<td style="text-align: left;">00:51:14.516</td>
</tr>
<tr class="odd">
<td>36</td>
<td style="text-align: left;">1866/9/1</td>
<td style="text-align: left;">1944/12/15</td>
<td style="text-align: left;">2001/09/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">13:49:04.331</td>
<td style="text-align: left;">19:41:30.672</td>
</tr>
<tr class="even">
<td>37</td>
<td style="text-align: left;">1866/10/1</td>
<td style="text-align: left;">1945/01/13</td>
<td style="text-align: left;">2001/10/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">21:27:09.517</td>
<td style="text-align: left;">10:16:11.944</td>
</tr>
<tr class="odd">
<td>38</td>
<td style="text-align: left;">1866/11/1</td>
<td style="text-align: left;">1945/02/12</td>
<td style="text-align: left;">2001/11/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">08:11:13.259</td>
<td style="text-align: left;">22:40:48.473</td>
</tr>
<tr class="even">
<td>39</td>
<td style="text-align: left;">1866/12/1</td>
<td style="text-align: left;">1945/03/13</td>
<td style="text-align: left;">2001/12/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">03:53:20.996</td>
<td style="text-align: left;">09:06:03.927</td>
</tr>
<tr class="odd">
<td>40</td>
<td style="text-align: left;">1885/9/1</td>
<td style="text-align: left;">1963/12/16</td>
<td style="text-align: left;">2020/09/01</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">11:48:39.726</td>
<td style="text-align: left;">06:32:25.892</td>
</tr>
<tr class="even">
<td>41</td>
<td style="text-align: left;">1885/9/1</td>
<td style="text-align: left;">1963/12/16</td>
<td style="text-align: left;">2020/09/01</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">11:48:39.726</td>
<td style="text-align: left;">06:32:25.892</td>
</tr>
<tr class="odd">
<td>42</td>
<td style="text-align: left;">1885/10/1</td>
<td style="text-align: left;">1964/01/14</td>
<td style="text-align: left;">2020/09/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">19:26:34.354</td>
<td style="text-align: left;">01:20:25.252</td>
</tr>
<tr class="even">
<td>43</td>
<td style="text-align: left;">1885/10/1</td>
<td style="text-align: left;">1964/01/14</td>
<td style="text-align: left;">2020/09/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">19:26:34.354</td>
<td style="text-align: left;">01:20:25.252</td>
</tr>
<tr class="odd">
<td>44</td>
<td style="text-align: left;">1885/11/1</td>
<td style="text-align: left;">1964/02/12</td>
<td style="text-align: left;">2020/11/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">06:10:38.096</td>
<td style="text-align: left;">17:47:57.629</td>
</tr>
<tr class="even">
<td>45</td>
<td style="text-align: left;">1885/12/1</td>
<td style="text-align: left;">1964/03/13</td>
<td style="text-align: left;">2020/12/29</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">01:52:56.390</td>
<td style="text-align: left;">07:20:04.127</td>
</tr>
<tr class="odd">
<td>46</td>
<td style="text-align: left;">1904/10/01</td>
<td style="text-align: left;">1983/01/14</td>
<td style="text-align: left;">2039/09/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">17:26:09.739</td>
<td style="text-align: left;">09:03:57.421</td>
</tr>
<tr class="even">
<td>47</td>
<td style="text-align: left;">1904/11/01</td>
<td style="text-align: left;">1983/02/12</td>
<td style="text-align: left;">2039/10/30</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">04:10:13.481</td>
<td style="text-align: left;">04:45:33.318</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<hr>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><em>Suvrnapuri</em> = City of Gold<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>Apara Ganita</em> = One with a lot of mathematical talent.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>saakshya</em> = witness (in Sanskrit)<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="metamutator/metamutator.github.io" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




</body></html>